#!/usr/bin/env bash

appDirName=".simple-editor-x"

if [ ! -d ~/${appDirName} ]; then # if not exist
    mkdir ~/${appDirName}
fi

currentDir=`dirname $0`

echo "copy source files to ~/${appDirName}"
echo "copy source files $(pwd)/. to ~/${appDirName}"
cp -a ${currentDir}/. ~/${appDirName}

echo "Create a shortcut to /usr/local/bin"
shortcutFile="sex"
chmod +x ${shortcutFile} # set execute permission
cp ${currentDir}/${shortcutFile} /usr/local/bin/${shortcutFile}

echo "Install successfully !!!"
echo "type 'sex ' on your terminal to use"